version: '3.7'

services:
  filehq_dev:
    image: postgres:latest
    container_name: wault_dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wault_dev
    volumes:
      - wault_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  wault_dev:
